---
title: " "
pagetitle: "Joe Zemmels"
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicicons.min.css"/>

My research focuses on pattern recognition and forensic statistics, with an emphasis on firearm and toolmark evidence. 
I am particularly interested in developing statistically-sound and accessible algorithms to objectively compare forensic evidence.

## Journal Articles

- **Zemmels, J.**, VanderPlas, S., Hofmann, H. *Automatic Matching of Cartridge Case Impressions*, (in preparation, to be submitted to The Journal of Data Science, Statistics, and Visualizations). 

- **Zemmels, J.**, VanderPlas, S., Hofmann, H. *Diagnostic Tools for Cartridge Case Comparison Algorithms*, (in preparation, to be submitted to The Journal of Computational and Graphical Statistics). 

- **Zemmels, J.**, VanderPlas, S., & Hofmann, H. (2023). *A Study in Reproducibility: The Congruent Matching Cells Algorithm and cmcR Package*. In The R Journal (Vol. 14, Issue 4, pp. 79–102). The R Foundation. https://doi.org/10.32614/rj-2023-014


## Contributed Talks

### Oral Presentations

- **Zemmels, J.**, VanderPlas, S., Hofmann, H. (2022). *An Accessible Open-Source Implementation of the Congruent Matching Cells Algorithms for Cartridge Case Analysis*, oral presentation at the American Academy of Forensic Science (AAFS) 74th Annual Meeting, Seattle, WA, February 21-25. ([slides](https://github.com/jzemmels/aafs22_slides/blob/main/slides/An%20Accessible%20Open-Source%20Implementation%20of%20the%20Congruent%20Matching%20Cells%20Algorithms%20for%20Cartridge%20Case%20Analysis%20D38.pptx))

### Poster Presentations

- **Zemmels, J.**, VanderPlas, S., Hofmann, H. (2023). *Visual Diagnostics for Cartridge Case Impression Evidence*, poster presentation at the American Academy of Forensic Science (AAFS) 75th Annual Meeting, Orlando, FL, February 13-17. ([poster](https://learn.forensicstats.org/product?catalog=PR2302Zemmels) accessible with free account sign-up)

  - Winner of "Outstanding Student Poster Award" at the AAFS 2023 Young Forensic Scientists Forum ([article](https://forensicstats.org/news-posts/csafe-graduate-student-wins-outstanding-poster-award-at-aafs-young-forensic-scientists-forum/))

- **Zemmels, J.**, VanderPlas, S., Hofmann, H. (2022). *A Cartridge Case Comparison Pipeline*, poster presentation at the International Association for Identification (IAI) 106th Annual Meeting, Omaha, NE, August 1-5.

- Tai, X., Eddy, W., **Zemmels, J.** (2019). *Developing Methods for Cartridge Breechface Images*, poster presentation at the CSAFE All-Hands meeting, Ames, IA, May 20-22.


### Webinar Presentations

- **Zemmels, J.**, Hofmann, H. (2023) *Visual Diagnostics for Algorithmic Cartridge Case Comparisons*, webinar presentation for the Center for Statistics and Applications in Forensic Evidence. March 29. ([slides](https://jzemmels.github.io/csafe-webinar-visualDiagnostics/#/title-slide), [github](https://github.com/jzemmels/csafe-webinar-visualDiagnostics), [recording](https://learn.forensicstats.org/product?catalog=WB230329) accessible with free account sign-up)

- **Zemmels, J.**, Schoen, A., Mack, D., Johnson, Z., Seeger C., Hanson, B. (2021). *DHR "Just the Facts" on Economic and Workforce Development*, webinar presentation for the Data Science for the Public Good Symposium, August 6.  ([event link](https://datascienceforthepublicgood.org/events/dspg2021/postersessions/dhr-just-facts-economic-and-workforce-development))

- **Zemmels, J.**, VanderPlas, S., Hofmann, H. (2020). *cmcR: Open-Source Implementation of the Congruent Matching Cells Method*, webinar presentation for Firearms and Toolmarks Workshop, November 31 - December 1. ([slides](https://github.com/jzemmels/cmcR_presentation))

## Software

### CRAN Packages

- [`cmcR`](https://github.com/CSAFE-ISU/cmcR): An Implementation of the 'Congruent Matching Cells' Method

### GitHub Packages

- [`impressions`](https://github.com/jzemmels/impressions): An R package for diagnosing cartridge case impression comparison algorithms

- [`scored`](https://github.com/jzemmels/scored): An R package to compare cartridge cases and compute similarity scores based on their breech face impressions.

### Interactive Applications

- [`cartridgeInvestigatR`](https://csafe.shinyapps.io/cartridgeInvestigatR/): process and compare cartridge case scans
